name: 'Modrinth Auto-Description'
description: 'Automatically update the description for a Modrinth project from a markdown file'
author: funnyboy-roks
inputs:
  auth-token:
    description: 'The autorisation token that can be found in your Modrinth cookies'
    required: true
  slug:
    description: 'The url/slug/id for the project.'
    required: true
  readme:
    description: 'The path to the file to use for the description'
    required: false
    default: 'README.md'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: arrow-up-right
  color: green
