name: 'Modrinth Auto-Description'
description: 'Automatically update the description for a Modrinth project from a markdown file'
author: funnyboy-roks
inputs:
  auth-token:
    description: 'The authorization token that can be found in your Modrinth cookies'
    required: true
  slug:
    description: 'The url/slug/id for the project.'
    required: true
  readme:
    description: 'The path to the file to use for the description'
    required: false
    default: 'README.md'
  project-name:
    description: 'Used in the user-agent for identification purposes'
    required: false
    default: '__unset'
  repo-token:
    description: 'GitHub token for accessing repository information (needed for private repos)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: arrow-up-right
  color: green
